# Generated by Django 5.1.1 on 2024-10-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('notes', '0002_collaborator_note_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='notes', to='labels.label'),
        ),
    ]
